In [11]:
import warnings
warnings.filterwarnings('ignore')

In [12]:
import pandas as pd
from plotnine import *

In [13]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 4820-D44C

 C:\Users\채송이\data\M3 디렉터리

2018-08-16  오후 12:22    <DIR>          .
2018-08-16  오후 12:22    <DIR>          ..
2018-08-16  오후 12:22    <DIR>          .ipynb_checkpoints
2018-08-08  오후 12:52               517 MALL.csv
2018-08-06  오후 06:25            55,924 multiprex.csv
2018-08-08  오후 01:53            24,742 Shoppingmall_code.ipynb
2018-08-16  오후 12:22             7,638 shoppingmall_info_template.csv
2018-08-13  오후 04:54            10,377 shoppingmall_info_template.xlsx
2018-08-14  오전 10:43            25,431 teampl_step1.ipynb
2018-08-14  오후 02:09               464 test.csv
2018-08-16  오후 12:19            64,748 updating_map.ipynb
2018-08-13  오후 04:58           105,759 전국 멀티플렉스 위치보기.ipynb
               9개 파일             295,600 바이트
               3개 디렉터리  57,344,536,576 바이트 남음

In [14]:
test = pd.read_csv('shoppingmall_info_template.csv', encoding='cp949')
test.shape

(10, 24)

In [15]:
test.head()

,Number,Name,Address,Latitude,Longitude,Multiflex_no,Traffic_subway,Traffic_subway_no,Traffic_subway_connection,Traffic_bus_green,...,Traffic_no,Car,Feeding,Stroller,Revenue,Store,Floor,Total area,Operation,Search_Word
0,1,스타필드 하남,"750 Misa-daero, 하남시 경기도 대한민국",37.545614,127.224064,1537,"잠실역, 강남역, 천호역, 상일동역, 방이역, 팔당역",6 (버스로 환승필),0,"23, 81, 82, 87",...,7,9.0,1,1,10388694.0,274,8,460000,신세계그룹,"하남 워터파크, 경기도 실내수영장, 스타필드 아쿠아, 스타필드 하남 맛집, 하남 스..."
1,2,스타필드 코엑스,대한민국 서울특별시 강남구 삼성1동 영동대로 513,37.511683,127.059108,3589,"삼성역, 봉은사역",3,1,3411,...,19,5.0,2,2,358392.0,274,4,463994,신세계그룹,"코엑스 놀거리, 코엑스 맛집, 코엑스 아쿠아리움, 코엑스 삐에로쇼핑, 킨텍스, 코엑..."
2,3,테크노마트 강변,대한민국 서울특별시 광진구 구의동 546-4,37.535117,127.095775,1663,강변역,1,1,"2224, 3212, 3214",...,37,3.0,2,1,1777539.0,886,15,259730,"프라임산업(주),삼원AMC(주)","강변 테크노마트 맛집, 강변 테크노마트 휴무, 신도림세상, 강변테크노마트 가구혼수백..."
3,4,아이파크몰 용산,대한민국 서울특별시 광진구 구의동 546-4,37.535117,127.095775,3893,"용산역, 신용산역",2,1,17,...,11,5.0,0,1,15476967.0,383,8,240110,HDC아이파크몰,"용산 아이파크몰 올리브영, 용산 쇼핑몰, 용산 아이파크 맛집, 용산 애니메이트, 용..."
4,5,가든파이브,대한민국 서울특별시 송파구 문정2동 충민로 66,37.477634,127.124943,1481,장지역,1,0,"3418, 3423",...,17,NaN,2,1,NaN,1527,16,426635,가든파이브라이프,"가든파이브 99안경할인점, 가든5 찜질방, 송파 스파인가든파이브, 현대아울렛 가든파..."

In [16]:
test.columns

Index(['Number', 'Name', 'Address', 'Latitude', 'Longitude', 'Multiflex_no',
       'Traffic_subway', 'Traffic_subway_no', 'Traffic_subway_connection',
       'Traffic_bus_green', 'Traffic_bus_red', 'Traffic_bus_blue',
       'Traffic_bus_express', 'Traffic_bus_shuttle', 'Traffic_no', 'Car',
       'Feeding', 'Stroller', 'Revenue', 'Store', 'Floor', 'Total area',
       'Operation', 'Search_Word'],
      dtype='object')

In [17]:
test.head()

,Number,Name,Address,Latitude,Longitude,Multiflex_no,Traffic_subway,Traffic_subway_no,Traffic_subway_connection,Traffic_bus_green,...,Traffic_no,Car,Feeding,Stroller,Revenue,Store,Floor,Total area,Operation,Search_Word
0,1,스타필드 하남,"750 Misa-daero, 하남시 경기도 대한민국",37.545614,127.224064,1537,"잠실역, 강남역, 천호역, 상일동역, 방이역, 팔당역",6 (버스로 환승필),0,"23, 81, 82, 87",...,7,9.0,1,1,10388694.0,274,8,460000,신세계그룹,"하남 워터파크, 경기도 실내수영장, 스타필드 아쿠아, 스타필드 하남 맛집, 하남 스..."
1,2,스타필드 코엑스,대한민국 서울특별시 강남구 삼성1동 영동대로 513,37.511683,127.059108,3589,"삼성역, 봉은사역",3,1,3411,...,19,5.0,2,2,358392.0,274,4,463994,신세계그룹,"코엑스 놀거리, 코엑스 맛집, 코엑스 아쿠아리움, 코엑스 삐에로쇼핑, 킨텍스, 코엑..."
2,3,테크노마트 강변,대한민국 서울특별시 광진구 구의동 546-4,37.535117,127.095775,1663,강변역,1,1,"2224, 3212, 3214",...,37,3.0,2,1,1777539.0,886,15,259730,"프라임산업(주),삼원AMC(주)","강변 테크노마트 맛집, 강변 테크노마트 휴무, 신도림세상, 강변테크노마트 가구혼수백..."
3,4,아이파크몰 용산,대한민국 서울특별시 광진구 구의동 546-4,37.535117,127.095775,3893,"용산역, 신용산역",2,1,17,...,11,5.0,0,1,15476967.0,383,8,240110,HDC아이파크몰,"용산 아이파크몰 올리브영, 용산 쇼핑몰, 용산 아이파크 맛집, 용산 애니메이트, 용..."
4,5,가든파이브,대한민국 서울특별시 송파구 문정2동 충민로 66,37.477634,127.124943,1481,장지역,1,0,"3418, 3423",...,17,NaN,2,1,NaN,1527,16,426635,가든파이브라이프,"가든파이브 99안경할인점, 가든5 찜질방, 송파 스파인가든파이브, 현대아울렛 가든파..."

In [18]:
test['Category'] = test['Name'].str.extract(r'^(스타필드|롯데몰)\s.*')
test

,Number,Name,Address,Latitude,Longitude,Multiflex_no,Traffic_subway,Traffic_subway_no,Traffic_subway_connection,Traffic_bus_green,...,Car,Feeding,Stroller,Revenue,Store,Floor,Total area,Operation,Search_Word,Category
0,1,스타필드 하남,"750 Misa-daero, 하남시 경기도 대한민국",37.545614,127.224064,1537,"잠실역, 강남역, 천호역, 상일동역, 방이역, 팔당역",6 (버스로 환승필),0,"23, 81, 82, 87",...,9.0,1,1,10388694.0,274,8,460000,신세계그룹,"하남 워터파크, 경기도 실내수영장, 스타필드 아쿠아, 스타필드 하남 맛집, 하남 스...",스타필드
1,2,스타필드 코엑스,대한민국 서울특별시 강남구 삼성1동 영동대로 513,37.511683,127.059108,3589,"삼성역, 봉은사역",3,1,3411,...,5.0,2,2,358392.0,274,4,463994,신세계그룹,"코엑스 놀거리, 코엑스 맛집, 코엑스 아쿠아리움, 코엑스 삐에로쇼핑, 킨텍스, 코엑...",스타필드
2,3,테크노마트 강변,대한민국 서울특별시 광진구 구의동 546-4,37.535117,127.095775,1663,강변역,1,1,"2224, 3212, 3214",...,3.0,2,1,1777539.0,886,15,259730,"프라임산업(주),삼원AMC(주)","강변 테크노마트 맛집, 강변 테크노마트 휴무, 신도림세상, 강변테크노마트 가구혼수백...",NaN
3,4,아이파크몰 용산,대한민국 서울특별시 광진구 구의동 546-4,37.535117,127.095775,3893,"용산역, 신용산역",2,1,17,...,5.0,0,1,15476967.0,383,8,240110,HDC아이파크몰,"용산 아이파크몰 올리브영, 용산 쇼핑몰, 용산 아이파크 맛집, 용산 애니메이트, 용...",NaN
4,5,가든파이브,대한민국 서울특별시 송파구 문정2동 충민로 66,37.477634,127.124943,1481,장지역,1,0,"3418, 3423",...,NaN,2,1,NaN,1527,16,426635,가든파이브라이프,"가든파이브 99안경할인점, 가든5 찜질방, 송파 스파인가든파이브, 현대아울렛 가든파...",NaN
5,6,타임스퀘어,대한민국 서울특별시 영등포구 영등포동 영중로 15,37.517164,126.903176,2797,"영등포역, 영등포시장역, 문래역, 신도림역",4,1,"5625, 6654, 9408, 5714, 6637, 6640A, 5714, 662...",...,6.0,1,2,16941342.0,189,7,340895,신세계그룹,"영등포 타임스퀘어 호텔, 영등포 타임스퀘어, 영등포 키즈앤키즈, 타임스퀘어 맛집, ...",NaN
6,7,디큐브시티,대한민국 서울특별시 구로구 신도림동 경인로 662,37.508432,126.888733,545,"신도림역 (1, 2호선)",1,1,"5615, 5714,6512,6513,6515,6637,6640, 6648, 664...",...,2.0,1,1,NaN,383,13,350025,현대백화점,"디큐브 피스트, 라그릴리아 신도림, 디큐브시티 아파트, 신도림 디큐브시티, 쉐라톤 ...",NaN
7,8,롯데몰 김포,대한민국 서울특별시 강서구 방화2동 하늘길 지하 77,37.566773,126.802512,2127,김포공항역,1,1,"2, 3, 12, 50, 56, 71, 150, 220, 50-1, 60, 60-3...",...,5.0,2,1,NaN,103,14,314000,롯데자산개발,"김포공항 롯데아울렛, 롯데마트 김포공항점, 김포 롯데몰 토끼정, 김포공항 롯데몰 롯...",롯데몰
8,9,롯데몰 은평,대한민국 서울특별시 은평구 진관동 통일로 1050,37.637515,126.917790,1336,구파발역,1,0,"7211, 7733, 8772, 17, 19, 30, 31, 34, 55, 99, ...",...,3.0,0,1,43000000.0,189,10,159760,롯데자산개발,"롯데시네아, 은평 롯데몰 롯데시네마, 롯데키즈파크, 은평 롯데몰 주차, 롯데시네마 ...",롯데몰
9,10,IFC몰,대한민국 서울특별시 영등포구 여의도동 국제금융로 10,37.525462,126.925454,1305,"여의도역 (5, 9호선)",1,1,"5012, 5615, 5618, 5623, 6513, 6623, 6628",...,NaN,1,1,NaN,111,3,76021,SIFC Property Korea,"서울 ifc몰, ifc몰 맛집, 여의도 IFC몰, ifc몰 주차, 여의도 ifc몰 ...",NaN

In [21]:
import folium
geo_df = test

map = folium.Map(location=[geo_df['Latitude'].mean(), geo_df['Longitude'].mean()], zoom_start=17, tiles='stamenwatercolor')

for i, row in geo_df.iterrows():
    mall_name = row['Name'] + '-' + row['Address']
    if row['Category'] == '롯데몰':
        icon = folium.Icon(color='red',icon='info-sign')
    elif row['Category'] == '스타필드':
        icon = folium.Icon(color='blue',icon='info-sign')
    else:
        icon = folium.Icon(color='green',icon='info-sign')

    folium.Marker(
        [row['Latitude'], row['Longitude']], 
        popup=mall_name,
        icon=icon
    ).add_to(map)

# for n in geo_df.index:
#     mall_name = geo_df['Name'][n] \
#               + '-' + geo_df['Address'][n]
        
#     folium.Marker([geo_df['latitude'][n], 
#                   geo_df['longitude'][n]], 
#                   popup=mall_name,
#                  icon=folium.Icon(color='pink',icon='info-sign'),                  
#                  ).add_to(map)

#     folium.Marker(
#                 location=[37.545614, 127.224064],
#                 popup = mall_name,
#                 icon=folium.Icon(icon='cloud')
#                 ).add_to(map)
#     folium.Marker(
#                 location=[37.511683, 127.059108],
#                 popup = mall_name,
#                 icon=folium.Icon(icon='cloud')
#                 ).add_to(map)
map

In [38]:
import folium
geo_df = test

map = folium.Map(location=[geo_df['Latitude'].mean(), geo_df['Longitude'].mean()], zoom_start=6, tiles='stamenwatercolor')

for i, row in geo_df.iterrows():
    mall_name = row['Name'] + '-' + row['Address']
    if row['Category'] == '롯데몰':
        icon = folium.Icon(color='red',icon='info-sign')
    elif row['Category'] == '스타필드':
        icon = folium.Icon(color='blue',icon='info-sign')
    else:
        icon = folium.Icon(color='green',icon='info-sign')

    folium.Marker(
        [row['Latitude'], row['Longitude']], 
        popup=mall_name,
        icon=icon
    ).add_to(map)

    
map.choropleth(
    geo_data = test,
    name='choropleth',
    data = test,
    columns=['Traffic_no'],
    key_on='feature.id',
    fill_color='Set1',
    fill_opacity=0.7,
    line_opacity=0.2,
)
folium.LayerControl().add_to(map)

IndexError: list index out of range

In [42]:
test['Traffic_no'] # 교통 가능 수

0     7
1    19
2    37
3    11
4    17
5    41
6    40
7    39
8    35
9    28
Name: Traffic_no, dtype: int64

In [40]:
import plotly.plotly as py

map = folium.Map(
    location=[geo_df['Latitude'].mean(),
    geo_df['Longitude'].mean()],
    zoom_start=6,
    tiles='stamenwatercolor')

map.choropleth(
    geo_data = test,
    name='choropleth',
    data = test,
    columns=['Traffic_no'],
    key_on='feature.id',
    fill_color='Set1',
    fill_opacity=0.7,
    line_opacity=0.2,
)
folium.LayerControl().add_to(map)

IndexError: list index out of range